### ISSUE TITLE
opencv python issue.

### ISSUE THREAD

**Issue by noobliman** [noobliman/Summer#1]
test2.py gives the following error:

```
(process:3981): GStreamer-CRITICAL **: 13:18:18.224: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
Traceback (most recent call last):
  File "test2.py", line 8, in <module>
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.0.0-pre) /opt/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

```

**Comment by Compro-Prasad** [comment]
This seems to be a problem with GStreamer.

**Comment by noobliman** [comment]
`    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
`
This line works when I do this :
```
imageSource = '/home/liman/Downloads/sample.png'
img = cv2.imread(imageSource)
```
So, I'm sure that it works when I use a pre-downloaded image. I believe that video capture is not working since my webcam too doesn't turn on. I'm also sure that my integrated webcam drive is installed since cheese recognises and successfully uses my webcam. I cannot understand how to make the webcam work for video capture in cv2.

**Comment by Compro-Prasad** [comment]
Looking up this issue I found out [this](https://github.com/alexa/avs-device-sdk/issues/262). Go through the thread and see if something helps you.

**Comment by Compro-Prasad** [comment]
Basically there might be some missing gst plugin you haven't installed yet.

**Comment by noobliman** [comment]
Seems like it is the issue 
![screenshot from 2018-06-25 14-58-25](https://user-images.githubusercontent.com/36070814/41842458-7a9b124c-7888-11e8-94c6-6114ca0cd877.png)

**Comment by noobliman** [comment]
After running : 
`sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools`
There doesn't seem to be any visible change : 
![screenshot from 2018-06-25 15-07-05](https://user-images.githubusercontent.com/36070814/41842918-bc604c64-7889-11e8-828f-80a616d1e927.png)

**Comment by Compro-Prasad** [comment]
It is `apt list --installed '*gst*'`

**Comment by noobliman** [comment]
Okay so ,
Earlier running `apt list --installed '*gst*'` too gave : 
`Listing... Done`
same output when I ran `apt list --installed 'gst'`
Now  running `apt list --installed 'gst'` gave : 
`Listing... Done`
But on running `apt list --installed '*gst*'` this is what I get : 
![screenshot from 2018-06-25 15-16-30](https://user-images.githubusercontent.com/36070814/41843436-28580f50-788b-11e8-978b-8414926c9f1c.png)

**Comment by Compro-Prasad** [comment]
I don't know much about face recognition. But I guess that you are missing some code here and there. If it is all okay from your side then it might be an issue on opencv side. Digging deeper is the best you can do. Open this issue with proper reproduction steps on opencv repo and see if they may help you out. And try to provide everything in text unless it is a graphical issue. When opening an issue there provide all versions of whatever software or package that you are using. Don't point them to a project. Instead give them a small sample code that produces the issue.

**Comment by noobliman** [comment]
Okay, now I'm sure it's not a gstreamer issue since it just worked for a pre-downloaded video.
On changing the code to : 
`video_capture = cv2.VideoCapture('sample_vid.mp4')`

**Comment by Compro-Prasad** [comment]
Can you detect live videos taken from your camera?

**Comment by noobliman** [comment]
Done, droid cam live feed working pretty well. Seems like it's a simple webcam issue.

**Comment by noobliman** [comment]
Solved by downgrading from 4.0.0 to 3.2.0 .

**Comment by cestpug** [comment]
how to downgrade 4.0.0 to 3.2.0 ? make some detail, please

**Comment by kaushiknagani** [comment]
An error is generated because your document may be corrupt or bad.

Add Exception in your code that will solve your problem.
`try:
		#code
  except cv2.error as e:
		pass`
